language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cordova-wakanda' ]; then cd .. && eval "mv $currentfolder generator-cordova-wakanda" && cd generator-cordova-wakanda; fi

